-- AUTO-GENERATED by scripts/gen-central-schema.mjs from ../cloudflare/migrations. DO NOT EDIT BY HAND.
-- Regenerate: node scripts/gen-central-schema.mjs
-- Central identity/registry/admin plane (shared D1). Per-tenant tables live in each WorkspaceDO.

CREATE TABLE IF NOT EXISTS workspaces (
  id TEXT PRIMARY KEY,
  legacy_source_id TEXT UNIQUE,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  owner_uid TEXT,
  currency TEXT NOT NULL DEFAULT 'ZAR',
  timezone TEXT NOT NULL DEFAULT 'Africa/Johannesburg',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS workspace_members (
  id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  auth_uid TEXT,
  email TEXT NOT NULL,
  display_name TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  role_key TEXT NOT NULL DEFAULT 'user',
  can_receive_low_stock_email INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(workspace_id, email)
);

CREATE INDEX IF NOT EXISTS idx_workspace_members_uid ON workspace_members(auth_uid);

CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  role_key TEXT NOT NULL,
  name TEXT NOT NULL,
  permissions_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(workspace_id, role_key)
);

CREATE TABLE IF NOT EXISTS admin_audit_events (
  id TEXT PRIMARY KEY,
  actor_uid TEXT,
  actor_email TEXT,
  action_type TEXT NOT NULL,
  target_id TEXT,
  details_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_events_created
  ON admin_audit_events(created_at);

CREATE TABLE IF NOT EXISTS app_users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  display_name TEXT,
  password_hash TEXT,
  password_salt TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  must_change_password INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  token TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id, expires_at);

CREATE TABLE IF NOT EXISTS workspace_registration_requests (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  full_name TEXT NOT NULL,
  site_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  workspace_id TEXT,
  requested_at TEXT NOT NULL DEFAULT (datetime('now')),
  reviewed_at TEXT,
  reviewed_by TEXT,
  raw_json TEXT NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_registration_requests_email ON workspace_registration_requests(email, status);

CREATE TABLE IF NOT EXISTS workspace_invitations (
  id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  display_name TEXT,
  role_key TEXT NOT NULL DEFAULT 'member',
  status TEXT NOT NULL DEFAULT 'pending',
  invited_by TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  accepted_at TEXT,
  raw_json TEXT NOT NULL DEFAULT '{}',
  UNIQUE(workspace_id, email)
);

CREATE INDEX IF NOT EXISTS idx_workspace_invitations_email ON workspace_invitations(email, status);

CREATE TABLE IF NOT EXISTS admin_users (
  id TEXT PRIMARY KEY,
  auth_uid TEXT,
  email TEXT NOT NULL UNIQUE,
  display_name TEXT,
  role_key TEXT NOT NULL DEFAULT 'superuser',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  created_by TEXT,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_admin_users_auth_uid ON admin_users(auth_uid, status);

CREATE INDEX IF NOT EXISTS idx_admin_users_email ON admin_users(email, status);

CREATE TABLE IF NOT EXISTS admin_system_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '{}',
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS auth_rate_limits (
  key TEXT PRIMARY KEY,
  attempts INTEGER NOT NULL DEFAULT 1,
  window_start INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_rate_limits_window ON auth_rate_limits(window_start);

CREATE TABLE IF NOT EXISTS auth_reset_tokens (
  token TEXT NOT NULL,
  user_id TEXT NOT NULL UNIQUE REFERENCES app_users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (token)
);

CREATE INDEX IF NOT EXISTS idx_auth_reset_tokens_user ON auth_reset_tokens(user_id);

-- workspace_members columns added at runtime by ensureMemberLocationsColumn() in the source app.
ALTER TABLE workspace_members ADD COLUMN allowed_locations_json TEXT DEFAULT NULL;
ALTER TABLE workspace_members ADD COLUMN can_access_external_transfers INTEGER NOT NULL DEFAULT 1;

-- Group ids promoted to the central registry for cross-workspace discovery (Phase 3c/3d).
ALTER TABLE workspaces ADD COLUMN org_id TEXT;
ALTER TABLE workspaces ADD COLUMN corp_id TEXT;
CREATE INDEX IF NOT EXISTS idx_workspaces_org ON workspaces(org_id);
CREATE INDEX IF NOT EXISTS idx_workspaces_corp ON workspaces(corp_id);

-- Cross-tenant coordination for EXTERNAL transfers (the shared source of truth for a transfer's
-- lifecycle; each side's WorkspaceDO holds its own local stock movements). NEW in cloudflare-v2.
CREATE TABLE IF NOT EXISTS external_transfers (
  id TEXT PRIMARY KEY,
  from_workspace_id TEXT NOT NULL,
  to_workspace_id TEXT NOT NULL,
  from_location_id TEXT,
  to_location_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending_receipt',
  items_json TEXT NOT NULL DEFAULT '[]',
  note TEXT,
  created_by TEXT,
  requested_at TEXT NOT NULL DEFAULT (datetime('now')),
  accepted_at TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_external_transfers_to ON external_transfers(to_workspace_id, status);
CREATE INDEX IF NOT EXISTS idx_external_transfers_from ON external_transfers(from_workspace_id, status);

-- Phase 35.2 customer-facing transaction reference foundation (also shipped as migration 0002
-- for existing central databases; IF NOT EXISTS keeps fresh installs safe).
CREATE TABLE IF NOT EXISTS transaction_reference_sequences (
  entity_type TEXT NOT NULL,
  date_key TEXT NOT NULL,
  last_sequence INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (entity_type, date_key)
);
CREATE TABLE IF NOT EXISTS transaction_references (
  reference TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL,
  prefix TEXT NOT NULL,
  date_key TEXT NOT NULL,
  sequence INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (entity_type, date_key, sequence)
);
CREATE TABLE IF NOT EXISTS transaction_reference_links (
  workspace_id TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  reference TEXT NOT NULL REFERENCES transaction_references(reference) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (workspace_id, entity_type, entity_id),
  UNIQUE (workspace_id, entity_type, reference)
);
CREATE INDEX IF NOT EXISTS idx_transaction_reference_links_reference
  ON transaction_reference_links(reference);
